[Fix] protect factors in iron()
liamgilbey/ggwaffle pull request #3
Opened 2022-08-01 02:25 UTC by DominiqueMakowski

Hi @liamgilbey, this is a fairly small but IMO vital fix that:

1) protect factors and doesn't coerce them to numeric (previous behavior did change factor levels to 1, 2, 3 etc)
2) Allows `mapping` argument to be a character indicating the column to iron on (the `aes_d` logic is a bit clunky when something simple is desired, so this would increase the flexibility. Also with this feature it makes it easy to program with)

In general, this allows for a more streamlined syntax and flexible waffles where one can change the factor levels and the order of the colors.

2022-08-01 02:28 UTC, DominiqueMakowski commented
example:

``` r
iris |> 
  dplyr::mutate(Species = forcats::fct_rev(Species)) |> 
  ggwaffle::waffle_iron("Species") |> 
  ggplot2::ggplot(ggplot2::aes(x, y, fill = group)) +
  ggwaffle::geom_waffle()
```

![](https://i.imgur.com/WKllhLV.png)

``` r

iris |> 
  ggwaffle::waffle_iron("Species") |> 
  ggplot2::ggplot(ggplot2::aes(x, y, fill = group)) +
  ggwaffle::geom_waffle()
```

![](https://i.imgur.com/eJ90CT8.png)

<sup>Created on 2022-08-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

2022-08-01 10:06 UTC, liamgilbey requested changes
Hi @DominiqueMakowski,

I agree about factors, nice spotting. I feel like your approach also negates the 
`na.rm` argument, so will review that.

I also agree that `aes_d_` is clunky, but it does have certain safeguards to supplying incorrect columns that I still feel are useful. Your approach of altering the columns directly negates the checks that `aes_d` provides.

[This commit](https://github.com/liamgilbey/ggwaffle/commit/821255d5a7ba3022ebe3825357deff3715fb0610) I just pushed through provides a new function, `aes_d_` that works with string arguments rather than the unquoted style arguments. There is no real benefit to this for normal use, but it does allow the ability to change your implementation slightly to this:

```r
  if(inherits(mapping, "character")){
    mapping <- aes_d_(group = mapping)
  }
```

This then flows through the intended `aes_d` workflow to provide validation, and allows the user to use the more flexible syntax of:

```r
iris |> 
  ggwaffle::waffle_iron("Species") |> 
  ggplot2::ggplot(ggplot2::aes(x, y, fill = group)) +
  ggwaffle::geom_waffle()
```

I feel this has the best of both worlds - does it give you the intended functionality?

2022-08-01 10:14 UTC, liamgilbey commented
The example provided works

``` r
# example works
iris |> 
  ggwaffle::waffle_iron("Species") |> 
  ggplot2::ggplot(ggplot2::aes(x, y, fill = group)) +
  ggwaffle::geom_waffle()
```

![](https://i.imgur.com/QCVIHAD.png)

Will fail if the column supplied is incorrect

``` r

# fails with invalid columns
iris |> 
  ggwaffle::waffle_iron("Speciez") |> 
  ggplot2::ggplot(ggplot2::aes(x, y, fill = group)) +
  ggwaffle::geom_waffle()
#> Error: Columns are not present in your dataset:
#>     Speciez
```

<sup>Created on 2022-08-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

2022-08-02 00:03 UTC, DominiqueMakowski commented
> I feel this has the best of both worlds

Yes I agree. Looking forward to see this merged :)

<sub>(also, this package definitely deserves to be on CRAN :)</sub>

2022-08-04 09:48 UTC, merged

2022-08-04 09:52 UTC, liamgilbey commented
Will be available soon.

Yes, I think it's time this made it's way onto CRAN for sure.